# Generated by Django 3.2 on 2021-11-20 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
        ),
        migrations.CreateModel(
            name='Instructer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('introduction', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('whereby', models.CharField(default='this lesson is not active', max_length=80)),
                ('price', models.IntegerField(default=1000)),
                ('lesson_date', models.DateTimeField(verbose_name='lesson date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('instructer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructer', to='yogapp.instructer')),
            ],
        ),
        migrations.CreateModel(
            name='LessonStyle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.CharField(choices=[('normal', 'ノーマル'), ('premium', 'プレミアム')], max_length=10)),
                ('capacity', models.IntegerField(default=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
        ),
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('1', 'レッスンについて'), ('2', 'インストラクターについて'), ('3', '要望'), ('4', 'その他')], max_length=10)),
                ('detail', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='yogapp.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='yogapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchased', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('stripe_id', models.CharField(max_length=200, null=True, verbose_name='stripe')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_lesson', to='yogapp.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoseCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poses', models.ManyToManyField(to='yogapp.Pose')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='poses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pose_collection', to='yogapp.posecollection'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_style', to='yogapp.lessonstyle'),
        ),
        migrations.AddField(
            model_name='answer',
            name='instructer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answered_instructer', to='yogapp.instructer'),
        ),
    ]
